---
title: "stock_analysis"
author: "Pradeep Raj Thapaliya"
date: "10/24/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Import Libraries

Import Required Libraries 
```{r}
library(ggplot2) 
library(Metrics) 
library(plotly)  # for interactive plots 
library(quantmod)
theme_set(theme_minimal())  

companies <- c("GOOGLE", "APPLE", "TESLA")

```


#Load Dataset

Loading datasets for Apple, Google and Tesla

```{r}

# Load the dataset
stock.df <- read.csv(file="data/all_company_stock.csv")
stock.df <- stock.df[, c("Open","High","Low","Close","Volume","Adjusted","Date", "Company.Name")]

stock.df$Date <- as.Date(stock.df$Date, format="%Y-%m-%d")

head(stock.df)
tail(stock.df) 

```

# Dimension of the data
```{r}
# getting dimensions
for (company in companies) {
  print(company)
  print(dim(stock.df[stock.df$Company.Name == company, ]))
}

```

# Variables and types
```{r}

# Inspect variables 
for (company in companies) {
  print(company)
  print(str(stock.df[stock.df$Company.Name == company, ]))
}
 
```

#Summary of Data

```{r}
#summary of the stocks for each company
for (company in companies) {
  print(company)
  print(summary(stock.df[stock.df$Company.Name == company, ]))
}

```
#Plots and Charts

Plotting close value over the time for each stock data set;

```{r}

## Graph Returns closing prices 
plt <- ggplot(stock.df, aes(x= Date, y = Close, colour = Company.Name)) +
  geom_line() + theme_bw() + labs(title = "", x = "Date", y= "Closing Price", subtitle = "")

ggplotly(plt)

```
```{r}

## Graph Returns Volume traded 
plt <- ggplot(stock.df, aes(x= Date, y = Volume, colour = Company.Name)) +
  geom_line() + theme_bw() + labs(title = "", x = "Date", y= "Volume", subtitle = "")

ggplotly(plt)

```



```{r}

# Area plot
ggplot(stock.df) + 
  geom_area(aes(x = Date, y = Close, color = Company.Name, fill = Company.Name), 
            alpha = 0.5, position = position_dodge(0.8)) +
  scale_color_manual(values = c("red", "gray" , "blue")) +
  scale_fill_manual(values =  c("red", "gray" , "blue"))


```


```{r}

df<- stock.df[stock.df$Company.Name == "GOOGLE", ]

# Multiple line plot
p <- ggplot(df) + 
  geom_line(aes(x = Date, y = Low, color = "Low")) + 
  geom_line(aes(x = Date, y = High, color = "High")) + 
  labs(title = "", x = "Date", y= "High and Low Values", subtitle = "Google Dataset", color = "Google") +
  theme_classic()

p
```

```{r}

df<- stock.df[stock.df$Company.Name == "APPLE", ]

# Multiple line plot
p <- ggplot(df) + 
  geom_line(aes(x = Date, y = Low, color = "Low")) + 
  geom_line(aes(x = Date, y = High, color = "High")) + 
  labs(title = "", x = "Date", y= "High and Low Values", subtitle = "Apple Dataset", color = "Apple") +
  theme_classic()

p
```

```{r}

df<- stock.df[stock.df$Company.Name == "TESLA", ]

# Multiple line plot
p <- ggplot(df) + 
  geom_line(aes(x = Date, y = Low, color = "Low")) + 
  geom_line(aes(x = Date, y = High, color = "High")) + 
  labs(title = "", x = "Date", y= "High and Low Values", subtitle = "Tesla Dataset", color = "Tesla") +
  theme_classic()

p
```

# Google Stock Analysis
```{r}
data <- stock.df[stock.df$Company.Name == "GOOGLE", ] 
rownames(data)<- data$Date 

data <- data[, c('Close', 'Open', 'High', 'Low', 'Volume', 'Adjusted')]
head(data)

chartSeries(data)

# Add Moving average convergence divergence 
addMACD()

# Add Bollinger Bands to the stock price
addBBands()

# Add Commodity Channel Index 
addCCI()

# Add Directional Movement Indicator
addADX()

# Add Money flow Chart
addCMF() 

# Highest and Lowest Point of Price
seriesHi(data[, c("Close")])
seriesLo(data[, c("Close")])

#Return Analysis
# Daily Returns
daily.return <- dailyReturn(data)
tail(daily.return)

# Weakly Returns
weekly.return <- weeklyReturn(data)
tail(weekly.return)

# Monthly Returns
monthly.return <- monthlyReturn(data)
tail(monthly.return)

# Yearly Returns
yearly.return <- yearlyReturn(data)
tail(yearly.return)


#all returns
all.returns <- allReturns(data)
head(all.returns)


```


# Apple Stock Analysis

```{r}

data <- stock.df[stock.df$Company.Name == "APPLE", ] 
rownames(data)<- data$Date 

data <- data[, c('Close', 'Open', 'High', 'Low', 'Volume', 'Adjusted')]
head(data)

chartSeries(data)

# Add Moving average convergence divergence 
addMACD()

# Add Bollinger Bands to the stock price
addBBands()

# Add Commodity Channel Index 
addCCI()

# Add Directional Movement Indicator
addADX()

# Add Money flow Chart
addCMF() 

# Highest and Lowest Point of Price
seriesHi(data[, c("Close")])
seriesLo(data[, c("Close")])

#Return Analysis
# Daily Returns
daily.return <- dailyReturn(data)
tail(daily.return)

# Weakly Returns
weekly.return <- weeklyReturn(data)
tail(weekly.return)

# Monthly Returns
monthly.return <- monthlyReturn(data)
tail(monthly.return)

# Yearly Returns
yearly.return <- yearlyReturn(data)
tail(yearly.return)


#all returns
all.returns <- allReturns(data)
head(all.returns)


```



#Tesla Stock Analysis

```{r}
data <- stock.df[stock.df$Company.Name == "TESLA", ] 
rownames(data)<- data$Date 

data <- data[, c('Close', 'Open', 'High', 'Low', 'Volume', 'Adjusted')]
head(data)

chartSeries(data)

# Add Moving average convergence divergence 
addMACD()

# Add Bollinger Bands to the stock price
addBBands()

# Add Commodity Channel Index 
addCCI()

# Add Directional Movement Indicator
addADX()

# Add Money flow Chart
addCMF() 

# Highest and Lowest Point of Price
seriesHi(data[, c("Close")])
seriesLo(data[, c("Close")])

#Return Analysis
# Daily Returns
daily.return <- dailyReturn(data)
tail(daily.return)

# Weakly Returns
weekly.return <- weeklyReturn(data)
tail(weekly.return)

# Monthly Returns
monthly.return <- monthlyReturn(data)
tail(monthly.return)

# Yearly Returns
yearly.return <- yearlyReturn(data)
tail(yearly.return)


#all returns
all.returns <- allReturns(data)
head(all.returns)


```


















